/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocumentsInvoicesRouteImport } from './routes/documents/invoices'
import { Route as DocumentUploadInvoiceRouteImport } from './routes/document-upload/invoice'
import { Route as DocumentUploadContractRouteImport } from './routes/document-upload/contract'
import { Route as AiChatRouteImport } from './routes/ai/chat'
import { Route as ApiInvoiceIndexRouteImport } from './routes/api/invoice/index'
import { Route as ApiValidationTestRouteImport } from './routes/api/validation/test'
import { Route as ApiValidationConfigsRouteImport } from './routes/api/validation/configs'
import { Route as ApiInvoiceDoc_idRouteImport } from './routes/api/invoice/$doc_id'
import { Route as ApiDocumentValidateRouteImport } from './routes/api/document/validate'
import { Route as ApiDocumentBirComplianceRouteImport } from './routes/api/document/bir-compliance'
import { Route as ApiDocumentBatchValidateRouteImport } from './routes/api/document/batch-validate'
import { Route as ApiDocumentBatchBirComplianceRouteImport } from './routes/api/document/batch-bir-compliance'
import { Route as ApiDocumentUploadInvoiceRouteImport } from './routes/api/document-upload/invoice'
import { Route as ApiDocumentUploadContractRouteImport } from './routes/api/document-upload/contract'
import { Route as ApiBirComplianceTestRouteImport } from './routes/api/bir-compliance/test'
import { Route as ApiAiInvoiceRouteImport } from './routes/api/ai/invoice'
import { Route as ApiDocumentDoc_idValidateRouteImport } from './routes/api/document/$doc_id/validate'
import { Route as ApiDocumentDoc_idBirComplianceRouteImport } from './routes/api/document/$doc_id/bir-compliance'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsInvoicesRoute = DocumentsInvoicesRouteImport.update({
  id: '/documents/invoices',
  path: '/documents/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentUploadInvoiceRoute = DocumentUploadInvoiceRouteImport.update({
  id: '/document-upload/invoice',
  path: '/document-upload/invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentUploadContractRoute = DocumentUploadContractRouteImport.update({
  id: '/document-upload/contract',
  path: '/document-upload/contract',
  getParentRoute: () => rootRouteImport,
} as any)
const AiChatRoute = AiChatRouteImport.update({
  id: '/ai/chat',
  path: '/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvoiceIndexRoute = ApiInvoiceIndexRouteImport.update({
  id: '/api/invoice/',
  path: '/api/invoice/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiValidationTestRoute = ApiValidationTestRouteImport.update({
  id: '/api/validation/test',
  path: '/api/validation/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiValidationConfigsRoute = ApiValidationConfigsRouteImport.update({
  id: '/api/validation/configs',
  path: '/api/validation/configs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvoiceDoc_idRoute = ApiInvoiceDoc_idRouteImport.update({
  id: '/api/invoice/$doc_id',
  path: '/api/invoice/$doc_id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentValidateRoute = ApiDocumentValidateRouteImport.update({
  id: '/api/document/validate',
  path: '/api/document/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentBirComplianceRoute =
  ApiDocumentBirComplianceRouteImport.update({
    id: '/api/document/bir-compliance',
    path: '/api/document/bir-compliance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDocumentBatchValidateRoute =
  ApiDocumentBatchValidateRouteImport.update({
    id: '/api/document/batch-validate',
    path: '/api/document/batch-validate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDocumentBatchBirComplianceRoute =
  ApiDocumentBatchBirComplianceRouteImport.update({
    id: '/api/document/batch-bir-compliance',
    path: '/api/document/batch-bir-compliance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDocumentUploadInvoiceRoute =
  ApiDocumentUploadInvoiceRouteImport.update({
    id: '/api/document-upload/invoice',
    path: '/api/document-upload/invoice',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDocumentUploadContractRoute =
  ApiDocumentUploadContractRouteImport.update({
    id: '/api/document-upload/contract',
    path: '/api/document-upload/contract',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBirComplianceTestRoute = ApiBirComplianceTestRouteImport.update({
  id: '/api/bir-compliance/test',
  path: '/api/bir-compliance/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiInvoiceRoute = ApiAiInvoiceRouteImport.update({
  id: '/api/ai/invoice',
  path: '/api/ai/invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentDoc_idValidateRoute =
  ApiDocumentDoc_idValidateRouteImport.update({
    id: '/api/document/$doc_id/validate',
    path: '/api/document/$doc_id/validate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDocumentDoc_idBirComplianceRoute =
  ApiDocumentDoc_idBirComplianceRouteImport.update({
    id: '/api/document/$doc_id/bir-compliance',
    path: '/api/document/$doc_id/bir-compliance',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai/chat': typeof AiChatRoute
  '/document-upload/contract': typeof DocumentUploadContractRoute
  '/document-upload/invoice': typeof DocumentUploadInvoiceRoute
  '/documents/invoices': typeof DocumentsInvoicesRoute
  '/api/ai/invoice': typeof ApiAiInvoiceRoute
  '/api/bir-compliance/test': typeof ApiBirComplianceTestRoute
  '/api/document-upload/contract': typeof ApiDocumentUploadContractRoute
  '/api/document-upload/invoice': typeof ApiDocumentUploadInvoiceRoute
  '/api/document/batch-bir-compliance': typeof ApiDocumentBatchBirComplianceRoute
  '/api/document/batch-validate': typeof ApiDocumentBatchValidateRoute
  '/api/document/bir-compliance': typeof ApiDocumentBirComplianceRoute
  '/api/document/validate': typeof ApiDocumentValidateRoute
  '/api/invoice/$doc_id': typeof ApiInvoiceDoc_idRoute
  '/api/validation/configs': typeof ApiValidationConfigsRoute
  '/api/validation/test': typeof ApiValidationTestRoute
  '/api/invoice': typeof ApiInvoiceIndexRoute
  '/api/document/$doc_id/bir-compliance': typeof ApiDocumentDoc_idBirComplianceRoute
  '/api/document/$doc_id/validate': typeof ApiDocumentDoc_idValidateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai/chat': typeof AiChatRoute
  '/document-upload/contract': typeof DocumentUploadContractRoute
  '/document-upload/invoice': typeof DocumentUploadInvoiceRoute
  '/documents/invoices': typeof DocumentsInvoicesRoute
  '/api/ai/invoice': typeof ApiAiInvoiceRoute
  '/api/bir-compliance/test': typeof ApiBirComplianceTestRoute
  '/api/document-upload/contract': typeof ApiDocumentUploadContractRoute
  '/api/document-upload/invoice': typeof ApiDocumentUploadInvoiceRoute
  '/api/document/batch-bir-compliance': typeof ApiDocumentBatchBirComplianceRoute
  '/api/document/batch-validate': typeof ApiDocumentBatchValidateRoute
  '/api/document/bir-compliance': typeof ApiDocumentBirComplianceRoute
  '/api/document/validate': typeof ApiDocumentValidateRoute
  '/api/invoice/$doc_id': typeof ApiInvoiceDoc_idRoute
  '/api/validation/configs': typeof ApiValidationConfigsRoute
  '/api/validation/test': typeof ApiValidationTestRoute
  '/api/invoice': typeof ApiInvoiceIndexRoute
  '/api/document/$doc_id/bir-compliance': typeof ApiDocumentDoc_idBirComplianceRoute
  '/api/document/$doc_id/validate': typeof ApiDocumentDoc_idValidateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai/chat': typeof AiChatRoute
  '/document-upload/contract': typeof DocumentUploadContractRoute
  '/document-upload/invoice': typeof DocumentUploadInvoiceRoute
  '/documents/invoices': typeof DocumentsInvoicesRoute
  '/api/ai/invoice': typeof ApiAiInvoiceRoute
  '/api/bir-compliance/test': typeof ApiBirComplianceTestRoute
  '/api/document-upload/contract': typeof ApiDocumentUploadContractRoute
  '/api/document-upload/invoice': typeof ApiDocumentUploadInvoiceRoute
  '/api/document/batch-bir-compliance': typeof ApiDocumentBatchBirComplianceRoute
  '/api/document/batch-validate': typeof ApiDocumentBatchValidateRoute
  '/api/document/bir-compliance': typeof ApiDocumentBirComplianceRoute
  '/api/document/validate': typeof ApiDocumentValidateRoute
  '/api/invoice/$doc_id': typeof ApiInvoiceDoc_idRoute
  '/api/validation/configs': typeof ApiValidationConfigsRoute
  '/api/validation/test': typeof ApiValidationTestRoute
  '/api/invoice/': typeof ApiInvoiceIndexRoute
  '/api/document/$doc_id/bir-compliance': typeof ApiDocumentDoc_idBirComplianceRoute
  '/api/document/$doc_id/validate': typeof ApiDocumentDoc_idValidateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai/chat'
    | '/document-upload/contract'
    | '/document-upload/invoice'
    | '/documents/invoices'
    | '/api/ai/invoice'
    | '/api/bir-compliance/test'
    | '/api/document-upload/contract'
    | '/api/document-upload/invoice'
    | '/api/document/batch-bir-compliance'
    | '/api/document/batch-validate'
    | '/api/document/bir-compliance'
    | '/api/document/validate'
    | '/api/invoice/$doc_id'
    | '/api/validation/configs'
    | '/api/validation/test'
    | '/api/invoice'
    | '/api/document/$doc_id/bir-compliance'
    | '/api/document/$doc_id/validate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai/chat'
    | '/document-upload/contract'
    | '/document-upload/invoice'
    | '/documents/invoices'
    | '/api/ai/invoice'
    | '/api/bir-compliance/test'
    | '/api/document-upload/contract'
    | '/api/document-upload/invoice'
    | '/api/document/batch-bir-compliance'
    | '/api/document/batch-validate'
    | '/api/document/bir-compliance'
    | '/api/document/validate'
    | '/api/invoice/$doc_id'
    | '/api/validation/configs'
    | '/api/validation/test'
    | '/api/invoice'
    | '/api/document/$doc_id/bir-compliance'
    | '/api/document/$doc_id/validate'
  id:
    | '__root__'
    | '/'
    | '/ai/chat'
    | '/document-upload/contract'
    | '/document-upload/invoice'
    | '/documents/invoices'
    | '/api/ai/invoice'
    | '/api/bir-compliance/test'
    | '/api/document-upload/contract'
    | '/api/document-upload/invoice'
    | '/api/document/batch-bir-compliance'
    | '/api/document/batch-validate'
    | '/api/document/bir-compliance'
    | '/api/document/validate'
    | '/api/invoice/$doc_id'
    | '/api/validation/configs'
    | '/api/validation/test'
    | '/api/invoice/'
    | '/api/document/$doc_id/bir-compliance'
    | '/api/document/$doc_id/validate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiChatRoute: typeof AiChatRoute
  DocumentUploadContractRoute: typeof DocumentUploadContractRoute
  DocumentUploadInvoiceRoute: typeof DocumentUploadInvoiceRoute
  DocumentsInvoicesRoute: typeof DocumentsInvoicesRoute
  ApiAiInvoiceRoute: typeof ApiAiInvoiceRoute
  ApiBirComplianceTestRoute: typeof ApiBirComplianceTestRoute
  ApiDocumentUploadContractRoute: typeof ApiDocumentUploadContractRoute
  ApiDocumentUploadInvoiceRoute: typeof ApiDocumentUploadInvoiceRoute
  ApiDocumentBatchBirComplianceRoute: typeof ApiDocumentBatchBirComplianceRoute
  ApiDocumentBatchValidateRoute: typeof ApiDocumentBatchValidateRoute
  ApiDocumentBirComplianceRoute: typeof ApiDocumentBirComplianceRoute
  ApiDocumentValidateRoute: typeof ApiDocumentValidateRoute
  ApiInvoiceDoc_idRoute: typeof ApiInvoiceDoc_idRoute
  ApiValidationConfigsRoute: typeof ApiValidationConfigsRoute
  ApiValidationTestRoute: typeof ApiValidationTestRoute
  ApiInvoiceIndexRoute: typeof ApiInvoiceIndexRoute
  ApiDocumentDoc_idBirComplianceRoute: typeof ApiDocumentDoc_idBirComplianceRoute
  ApiDocumentDoc_idValidateRoute: typeof ApiDocumentDoc_idValidateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/invoices': {
      id: '/documents/invoices'
      path: '/documents/invoices'
      fullPath: '/documents/invoices'
      preLoaderRoute: typeof DocumentsInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document-upload/invoice': {
      id: '/document-upload/invoice'
      path: '/document-upload/invoice'
      fullPath: '/document-upload/invoice'
      preLoaderRoute: typeof DocumentUploadInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document-upload/contract': {
      id: '/document-upload/contract'
      path: '/document-upload/contract'
      fullPath: '/document-upload/contract'
      preLoaderRoute: typeof DocumentUploadContractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/chat': {
      id: '/ai/chat'
      path: '/ai/chat'
      fullPath: '/ai/chat'
      preLoaderRoute: typeof AiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invoice/': {
      id: '/api/invoice/'
      path: '/api/invoice'
      fullPath: '/api/invoice'
      preLoaderRoute: typeof ApiInvoiceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/validation/test': {
      id: '/api/validation/test'
      path: '/api/validation/test'
      fullPath: '/api/validation/test'
      preLoaderRoute: typeof ApiValidationTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/validation/configs': {
      id: '/api/validation/configs'
      path: '/api/validation/configs'
      fullPath: '/api/validation/configs'
      preLoaderRoute: typeof ApiValidationConfigsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invoice/$doc_id': {
      id: '/api/invoice/$doc_id'
      path: '/api/invoice/$doc_id'
      fullPath: '/api/invoice/$doc_id'
      preLoaderRoute: typeof ApiInvoiceDoc_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/document/validate': {
      id: '/api/document/validate'
      path: '/api/document/validate'
      fullPath: '/api/document/validate'
      preLoaderRoute: typeof ApiDocumentValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/document/bir-compliance': {
      id: '/api/document/bir-compliance'
      path: '/api/document/bir-compliance'
      fullPath: '/api/document/bir-compliance'
      preLoaderRoute: typeof ApiDocumentBirComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/document/batch-validate': {
      id: '/api/document/batch-validate'
      path: '/api/document/batch-validate'
      fullPath: '/api/document/batch-validate'
      preLoaderRoute: typeof ApiDocumentBatchValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/document/batch-bir-compliance': {
      id: '/api/document/batch-bir-compliance'
      path: '/api/document/batch-bir-compliance'
      fullPath: '/api/document/batch-bir-compliance'
      preLoaderRoute: typeof ApiDocumentBatchBirComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/document-upload/invoice': {
      id: '/api/document-upload/invoice'
      path: '/api/document-upload/invoice'
      fullPath: '/api/document-upload/invoice'
      preLoaderRoute: typeof ApiDocumentUploadInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/document-upload/contract': {
      id: '/api/document-upload/contract'
      path: '/api/document-upload/contract'
      fullPath: '/api/document-upload/contract'
      preLoaderRoute: typeof ApiDocumentUploadContractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bir-compliance/test': {
      id: '/api/bir-compliance/test'
      path: '/api/bir-compliance/test'
      fullPath: '/api/bir-compliance/test'
      preLoaderRoute: typeof ApiBirComplianceTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/invoice': {
      id: '/api/ai/invoice'
      path: '/api/ai/invoice'
      fullPath: '/api/ai/invoice'
      preLoaderRoute: typeof ApiAiInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/document/$doc_id/validate': {
      id: '/api/document/$doc_id/validate'
      path: '/api/document/$doc_id/validate'
      fullPath: '/api/document/$doc_id/validate'
      preLoaderRoute: typeof ApiDocumentDoc_idValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/document/$doc_id/bir-compliance': {
      id: '/api/document/$doc_id/bir-compliance'
      path: '/api/document/$doc_id/bir-compliance'
      fullPath: '/api/document/$doc_id/bir-compliance'
      preLoaderRoute: typeof ApiDocumentDoc_idBirComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiChatRoute: AiChatRoute,
  DocumentUploadContractRoute: DocumentUploadContractRoute,
  DocumentUploadInvoiceRoute: DocumentUploadInvoiceRoute,
  DocumentsInvoicesRoute: DocumentsInvoicesRoute,
  ApiAiInvoiceRoute: ApiAiInvoiceRoute,
  ApiBirComplianceTestRoute: ApiBirComplianceTestRoute,
  ApiDocumentUploadContractRoute: ApiDocumentUploadContractRoute,
  ApiDocumentUploadInvoiceRoute: ApiDocumentUploadInvoiceRoute,
  ApiDocumentBatchBirComplianceRoute: ApiDocumentBatchBirComplianceRoute,
  ApiDocumentBatchValidateRoute: ApiDocumentBatchValidateRoute,
  ApiDocumentBirComplianceRoute: ApiDocumentBirComplianceRoute,
  ApiDocumentValidateRoute: ApiDocumentValidateRoute,
  ApiInvoiceDoc_idRoute: ApiInvoiceDoc_idRoute,
  ApiValidationConfigsRoute: ApiValidationConfigsRoute,
  ApiValidationTestRoute: ApiValidationTestRoute,
  ApiInvoiceIndexRoute: ApiInvoiceIndexRoute,
  ApiDocumentDoc_idBirComplianceRoute: ApiDocumentDoc_idBirComplianceRoute,
  ApiDocumentDoc_idValidateRoute: ApiDocumentDoc_idValidateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
