/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocumentUploadInvoiceRouteImport } from './routes/document-upload/invoice'
import { Route as DocumentUploadContractRouteImport } from './routes/document-upload/contract'
import { Route as AiChatRouteImport } from './routes/ai/chat'
import { Route as DocumentsInvoicesIndexRouteImport } from './routes/documents/invoices/index'
import { Route as ApiInvoiceIndexRouteImport } from './routes/api/invoice/index'
<<<<<<< HEAD
import { Route as ApiValidationTestRouteImport } from './routes/api/validation/test'
import { Route as ApiValidationConfigsRouteImport } from './routes/api/validation/configs'
=======
import { Route as DocumentsInvoicesIdRouteImport } from './routes/documents/invoices/$id'
>>>>>>> feature/vince
import { Route as ApiInvoiceDoc_idRouteImport } from './routes/api/invoice/$doc_id'
import { Route as ApiDocumentValidateRouteImport } from './routes/api/document/validate'
import { Route as ApiDocumentBirComplianceRouteImport } from './routes/api/document/bir-compliance'
import { Route as ApiDocumentBatchValidateRouteImport } from './routes/api/document/batch-validate'
import { Route as ApiDocumentBatchBirComplianceRouteImport } from './routes/api/document/batch-bir-compliance'
import { Route as ApiDocumentUploadInvoiceRouteImport } from './routes/api/document-upload/invoice'
import { Route as ApiDocumentUploadContractRouteImport } from './routes/api/document-upload/contract'
import { Route as ApiBirComplianceTestRouteImport } from './routes/api/bir-compliance/test'
import { Route as ApiAiInvoiceIndexRouteImport } from './routes/api/ai/invoice/index'
<<<<<<< HEAD
import { Route as ApiDocumentDoc_idValidateRouteImport } from './routes/api/document/$doc_id/validate'
import { Route as ApiDocumentDoc_idBirComplianceRouteImport } from './routes/api/document/$doc_id/bir-compliance'
=======
import { Route as ApiInvoicePdfDocIdRouteImport } from './routes/api/invoice/pdf.$docId'
>>>>>>> feature/vince
import { Route as ApiAiInvoiceInvoiceNoRouteImport } from './routes/api/ai/invoice/$invoiceNo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentUploadInvoiceRoute = DocumentUploadInvoiceRouteImport.update({
  id: '/document-upload/invoice',
  path: '/document-upload/invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentUploadContractRoute = DocumentUploadContractRouteImport.update({
  id: '/document-upload/contract',
  path: '/document-upload/contract',
  getParentRoute: () => rootRouteImport,
} as any)
const AiChatRoute = AiChatRouteImport.update({
  id: '/ai/chat',
  path: '/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsInvoicesIndexRoute = DocumentsInvoicesIndexRouteImport.update({
  id: '/documents/invoices/',
  path: '/documents/invoices/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvoiceIndexRoute = ApiInvoiceIndexRouteImport.update({
  id: '/api/invoice/',
  path: '/api/invoice/',
  getParentRoute: () => rootRouteImport,
} as any)
<<<<<<< HEAD
const ApiValidationTestRoute = ApiValidationTestRouteImport.update({
  id: '/api/validation/test',
  path: '/api/validation/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiValidationConfigsRoute = ApiValidationConfigsRouteImport.update({
  id: '/api/validation/configs',
  path: '/api/validation/configs',
=======
const DocumentsInvoicesIdRoute = DocumentsInvoicesIdRouteImport.update({
  id: '/documents/invoices/$id',
  path: '/documents/invoices/$id',
>>>>>>> feature/vince
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvoiceDoc_idRoute = ApiInvoiceDoc_idRouteImport.update({
  id: '/api/invoice/$doc_id',
  path: '/api/invoice/$doc_id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentValidateRoute = ApiDocumentValidateRouteImport.update({
  id: '/api/document/validate',
  path: '/api/document/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentBirComplianceRoute =
  ApiDocumentBirComplianceRouteImport.update({
    id: '/api/document/bir-compliance',
    path: '/api/document/bir-compliance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDocumentBatchValidateRoute =
  ApiDocumentBatchValidateRouteImport.update({
    id: '/api/document/batch-validate',
    path: '/api/document/batch-validate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDocumentBatchBirComplianceRoute =
  ApiDocumentBatchBirComplianceRouteImport.update({
    id: '/api/document/batch-bir-compliance',
    path: '/api/document/batch-bir-compliance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDocumentUploadInvoiceRoute =
  ApiDocumentUploadInvoiceRouteImport.update({
    id: '/api/document-upload/invoice',
    path: '/api/document-upload/invoice',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDocumentUploadContractRoute =
  ApiDocumentUploadContractRouteImport.update({
    id: '/api/document-upload/contract',
    path: '/api/document-upload/contract',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBirComplianceTestRoute = ApiBirComplianceTestRouteImport.update({
  id: '/api/bir-compliance/test',
  path: '/api/bir-compliance/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiInvoiceIndexRoute = ApiAiInvoiceIndexRouteImport.update({
  id: '/api/ai/invoice/',
  path: '/api/ai/invoice/',
  getParentRoute: () => rootRouteImport,
} as any)
<<<<<<< HEAD
const ApiDocumentDoc_idValidateRoute =
  ApiDocumentDoc_idValidateRouteImport.update({
    id: '/api/document/$doc_id/validate',
    path: '/api/document/$doc_id/validate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDocumentDoc_idBirComplianceRoute =
  ApiDocumentDoc_idBirComplianceRouteImport.update({
    id: '/api/document/$doc_id/bir-compliance',
    path: '/api/document/$doc_id/bir-compliance',
    getParentRoute: () => rootRouteImport,
  } as any)
=======
const ApiInvoicePdfDocIdRoute = ApiInvoicePdfDocIdRouteImport.update({
  id: '/api/invoice/pdf/$docId',
  path: '/api/invoice/pdf/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
>>>>>>> feature/vince
const ApiAiInvoiceInvoiceNoRoute = ApiAiInvoiceInvoiceNoRouteImport.update({
  id: '/api/ai/invoice/$invoiceNo',
  path: '/api/ai/invoice/$invoiceNo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai/chat': typeof AiChatRoute
  '/document-upload/contract': typeof DocumentUploadContractRoute
  '/document-upload/invoice': typeof DocumentUploadInvoiceRoute
<<<<<<< HEAD
  '/documents/invoices': typeof DocumentsInvoicesRoute
  '/api/bir-compliance/test': typeof ApiBirComplianceTestRoute
=======
>>>>>>> feature/vince
  '/api/document-upload/contract': typeof ApiDocumentUploadContractRoute
  '/api/document-upload/invoice': typeof ApiDocumentUploadInvoiceRoute
  '/api/document/batch-bir-compliance': typeof ApiDocumentBatchBirComplianceRoute
  '/api/document/batch-validate': typeof ApiDocumentBatchValidateRoute
  '/api/document/bir-compliance': typeof ApiDocumentBirComplianceRoute
  '/api/document/validate': typeof ApiDocumentValidateRoute
  '/api/invoice/$doc_id': typeof ApiInvoiceDoc_idRoute
<<<<<<< HEAD
  '/api/validation/configs': typeof ApiValidationConfigsRoute
  '/api/validation/test': typeof ApiValidationTestRoute
=======
  '/documents/invoices/$id': typeof DocumentsInvoicesIdRoute
>>>>>>> feature/vince
  '/api/invoice': typeof ApiInvoiceIndexRoute
  '/documents/invoices': typeof DocumentsInvoicesIndexRoute
  '/api/ai/invoice/$invoiceNo': typeof ApiAiInvoiceInvoiceNoRoute
<<<<<<< HEAD
  '/api/document/$doc_id/bir-compliance': typeof ApiDocumentDoc_idBirComplianceRoute
  '/api/document/$doc_id/validate': typeof ApiDocumentDoc_idValidateRoute
=======
  '/api/invoice/pdf/$docId': typeof ApiInvoicePdfDocIdRoute
>>>>>>> feature/vince
  '/api/ai/invoice': typeof ApiAiInvoiceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai/chat': typeof AiChatRoute
  '/document-upload/contract': typeof DocumentUploadContractRoute
  '/document-upload/invoice': typeof DocumentUploadInvoiceRoute
<<<<<<< HEAD
  '/documents/invoices': typeof DocumentsInvoicesRoute
  '/api/bir-compliance/test': typeof ApiBirComplianceTestRoute
=======
>>>>>>> feature/vince
  '/api/document-upload/contract': typeof ApiDocumentUploadContractRoute
  '/api/document-upload/invoice': typeof ApiDocumentUploadInvoiceRoute
  '/api/document/batch-bir-compliance': typeof ApiDocumentBatchBirComplianceRoute
  '/api/document/batch-validate': typeof ApiDocumentBatchValidateRoute
  '/api/document/bir-compliance': typeof ApiDocumentBirComplianceRoute
  '/api/document/validate': typeof ApiDocumentValidateRoute
  '/api/invoice/$doc_id': typeof ApiInvoiceDoc_idRoute
<<<<<<< HEAD
  '/api/validation/configs': typeof ApiValidationConfigsRoute
  '/api/validation/test': typeof ApiValidationTestRoute
=======
  '/documents/invoices/$id': typeof DocumentsInvoicesIdRoute
>>>>>>> feature/vince
  '/api/invoice': typeof ApiInvoiceIndexRoute
  '/documents/invoices': typeof DocumentsInvoicesIndexRoute
  '/api/ai/invoice/$invoiceNo': typeof ApiAiInvoiceInvoiceNoRoute
<<<<<<< HEAD
  '/api/document/$doc_id/bir-compliance': typeof ApiDocumentDoc_idBirComplianceRoute
  '/api/document/$doc_id/validate': typeof ApiDocumentDoc_idValidateRoute
=======
  '/api/invoice/pdf/$docId': typeof ApiInvoicePdfDocIdRoute
>>>>>>> feature/vince
  '/api/ai/invoice': typeof ApiAiInvoiceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai/chat': typeof AiChatRoute
  '/document-upload/contract': typeof DocumentUploadContractRoute
  '/document-upload/invoice': typeof DocumentUploadInvoiceRoute
<<<<<<< HEAD
  '/documents/invoices': typeof DocumentsInvoicesRoute
  '/api/bir-compliance/test': typeof ApiBirComplianceTestRoute
=======
>>>>>>> feature/vince
  '/api/document-upload/contract': typeof ApiDocumentUploadContractRoute
  '/api/document-upload/invoice': typeof ApiDocumentUploadInvoiceRoute
  '/api/document/batch-bir-compliance': typeof ApiDocumentBatchBirComplianceRoute
  '/api/document/batch-validate': typeof ApiDocumentBatchValidateRoute
  '/api/document/bir-compliance': typeof ApiDocumentBirComplianceRoute
  '/api/document/validate': typeof ApiDocumentValidateRoute
  '/api/invoice/$doc_id': typeof ApiInvoiceDoc_idRoute
<<<<<<< HEAD
  '/api/validation/configs': typeof ApiValidationConfigsRoute
  '/api/validation/test': typeof ApiValidationTestRoute
=======
  '/documents/invoices/$id': typeof DocumentsInvoicesIdRoute
>>>>>>> feature/vince
  '/api/invoice/': typeof ApiInvoiceIndexRoute
  '/documents/invoices/': typeof DocumentsInvoicesIndexRoute
  '/api/ai/invoice/$invoiceNo': typeof ApiAiInvoiceInvoiceNoRoute
<<<<<<< HEAD
  '/api/document/$doc_id/bir-compliance': typeof ApiDocumentDoc_idBirComplianceRoute
  '/api/document/$doc_id/validate': typeof ApiDocumentDoc_idValidateRoute
=======
  '/api/invoice/pdf/$docId': typeof ApiInvoicePdfDocIdRoute
>>>>>>> feature/vince
  '/api/ai/invoice/': typeof ApiAiInvoiceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai/chat'
    | '/document-upload/contract'
    | '/document-upload/invoice'
<<<<<<< HEAD
    | '/documents/invoices'
    | '/api/bir-compliance/test'
=======
>>>>>>> feature/vince
    | '/api/document-upload/contract'
    | '/api/document-upload/invoice'
    | '/api/document/batch-bir-compliance'
    | '/api/document/batch-validate'
    | '/api/document/bir-compliance'
    | '/api/document/validate'
    | '/api/invoice/$doc_id'
<<<<<<< HEAD
    | '/api/validation/configs'
    | '/api/validation/test'
=======
    | '/documents/invoices/$id'
>>>>>>> feature/vince
    | '/api/invoice'
    | '/documents/invoices'
    | '/api/ai/invoice/$invoiceNo'
<<<<<<< HEAD
    | '/api/document/$doc_id/bir-compliance'
    | '/api/document/$doc_id/validate'
=======
    | '/api/invoice/pdf/$docId'
>>>>>>> feature/vince
    | '/api/ai/invoice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai/chat'
    | '/document-upload/contract'
    | '/document-upload/invoice'
<<<<<<< HEAD
    | '/documents/invoices'
    | '/api/bir-compliance/test'
=======
>>>>>>> feature/vince
    | '/api/document-upload/contract'
    | '/api/document-upload/invoice'
    | '/api/document/batch-bir-compliance'
    | '/api/document/batch-validate'
    | '/api/document/bir-compliance'
    | '/api/document/validate'
    | '/api/invoice/$doc_id'
<<<<<<< HEAD
    | '/api/validation/configs'
    | '/api/validation/test'
=======
    | '/documents/invoices/$id'
>>>>>>> feature/vince
    | '/api/invoice'
    | '/documents/invoices'
    | '/api/ai/invoice/$invoiceNo'
<<<<<<< HEAD
    | '/api/document/$doc_id/bir-compliance'
    | '/api/document/$doc_id/validate'
=======
    | '/api/invoice/pdf/$docId'
>>>>>>> feature/vince
    | '/api/ai/invoice'
  id:
    | '__root__'
    | '/'
    | '/ai/chat'
    | '/document-upload/contract'
    | '/document-upload/invoice'
<<<<<<< HEAD
    | '/documents/invoices'
    | '/api/bir-compliance/test'
=======
>>>>>>> feature/vince
    | '/api/document-upload/contract'
    | '/api/document-upload/invoice'
    | '/api/document/batch-bir-compliance'
    | '/api/document/batch-validate'
    | '/api/document/bir-compliance'
    | '/api/document/validate'
    | '/api/invoice/$doc_id'
<<<<<<< HEAD
    | '/api/validation/configs'
    | '/api/validation/test'
=======
    | '/documents/invoices/$id'
>>>>>>> feature/vince
    | '/api/invoice/'
    | '/documents/invoices/'
    | '/api/ai/invoice/$invoiceNo'
<<<<<<< HEAD
    | '/api/document/$doc_id/bir-compliance'
    | '/api/document/$doc_id/validate'
=======
    | '/api/invoice/pdf/$docId'
>>>>>>> feature/vince
    | '/api/ai/invoice/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiChatRoute: typeof AiChatRoute
  DocumentUploadContractRoute: typeof DocumentUploadContractRoute
  DocumentUploadInvoiceRoute: typeof DocumentUploadInvoiceRoute
<<<<<<< HEAD
  DocumentsInvoicesRoute: typeof DocumentsInvoicesRoute
  ApiBirComplianceTestRoute: typeof ApiBirComplianceTestRoute
=======
>>>>>>> feature/vince
  ApiDocumentUploadContractRoute: typeof ApiDocumentUploadContractRoute
  ApiDocumentUploadInvoiceRoute: typeof ApiDocumentUploadInvoiceRoute
  ApiDocumentBatchBirComplianceRoute: typeof ApiDocumentBatchBirComplianceRoute
  ApiDocumentBatchValidateRoute: typeof ApiDocumentBatchValidateRoute
  ApiDocumentBirComplianceRoute: typeof ApiDocumentBirComplianceRoute
  ApiDocumentValidateRoute: typeof ApiDocumentValidateRoute
  ApiInvoiceDoc_idRoute: typeof ApiInvoiceDoc_idRoute
<<<<<<< HEAD
  ApiValidationConfigsRoute: typeof ApiValidationConfigsRoute
  ApiValidationTestRoute: typeof ApiValidationTestRoute
=======
  DocumentsInvoicesIdRoute: typeof DocumentsInvoicesIdRoute
>>>>>>> feature/vince
  ApiInvoiceIndexRoute: typeof ApiInvoiceIndexRoute
  DocumentsInvoicesIndexRoute: typeof DocumentsInvoicesIndexRoute
  ApiAiInvoiceInvoiceNoRoute: typeof ApiAiInvoiceInvoiceNoRoute
<<<<<<< HEAD
  ApiDocumentDoc_idBirComplianceRoute: typeof ApiDocumentDoc_idBirComplianceRoute
  ApiDocumentDoc_idValidateRoute: typeof ApiDocumentDoc_idValidateRoute
=======
  ApiInvoicePdfDocIdRoute: typeof ApiInvoicePdfDocIdRoute
>>>>>>> feature/vince
  ApiAiInvoiceIndexRoute: typeof ApiAiInvoiceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document-upload/invoice': {
      id: '/document-upload/invoice'
      path: '/document-upload/invoice'
      fullPath: '/document-upload/invoice'
      preLoaderRoute: typeof DocumentUploadInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document-upload/contract': {
      id: '/document-upload/contract'
      path: '/document-upload/contract'
      fullPath: '/document-upload/contract'
      preLoaderRoute: typeof DocumentUploadContractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/chat': {
      id: '/ai/chat'
      path: '/ai/chat'
      fullPath: '/ai/chat'
      preLoaderRoute: typeof AiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/invoices/': {
      id: '/documents/invoices/'
      path: '/documents/invoices'
      fullPath: '/documents/invoices'
      preLoaderRoute: typeof DocumentsInvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invoice/': {
      id: '/api/invoice/'
      path: '/api/invoice'
      fullPath: '/api/invoice'
      preLoaderRoute: typeof ApiInvoiceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
<<<<<<< HEAD
    '/api/validation/test': {
      id: '/api/validation/test'
      path: '/api/validation/test'
      fullPath: '/api/validation/test'
      preLoaderRoute: typeof ApiValidationTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/validation/configs': {
      id: '/api/validation/configs'
      path: '/api/validation/configs'
      fullPath: '/api/validation/configs'
      preLoaderRoute: typeof ApiValidationConfigsRouteImport
=======
    '/documents/invoices/$id': {
      id: '/documents/invoices/$id'
      path: '/documents/invoices/$id'
      fullPath: '/documents/invoices/$id'
      preLoaderRoute: typeof DocumentsInvoicesIdRouteImport
>>>>>>> feature/vince
      parentRoute: typeof rootRouteImport
    }
    '/api/invoice/$doc_id': {
      id: '/api/invoice/$doc_id'
      path: '/api/invoice/$doc_id'
      fullPath: '/api/invoice/$doc_id'
      preLoaderRoute: typeof ApiInvoiceDoc_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/document/validate': {
      id: '/api/document/validate'
      path: '/api/document/validate'
      fullPath: '/api/document/validate'
      preLoaderRoute: typeof ApiDocumentValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/document/bir-compliance': {
      id: '/api/document/bir-compliance'
      path: '/api/document/bir-compliance'
      fullPath: '/api/document/bir-compliance'
      preLoaderRoute: typeof ApiDocumentBirComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/document/batch-validate': {
      id: '/api/document/batch-validate'
      path: '/api/document/batch-validate'
      fullPath: '/api/document/batch-validate'
      preLoaderRoute: typeof ApiDocumentBatchValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/document/batch-bir-compliance': {
      id: '/api/document/batch-bir-compliance'
      path: '/api/document/batch-bir-compliance'
      fullPath: '/api/document/batch-bir-compliance'
      preLoaderRoute: typeof ApiDocumentBatchBirComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/document-upload/invoice': {
      id: '/api/document-upload/invoice'
      path: '/api/document-upload/invoice'
      fullPath: '/api/document-upload/invoice'
      preLoaderRoute: typeof ApiDocumentUploadInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/document-upload/contract': {
      id: '/api/document-upload/contract'
      path: '/api/document-upload/contract'
      fullPath: '/api/document-upload/contract'
      preLoaderRoute: typeof ApiDocumentUploadContractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bir-compliance/test': {
      id: '/api/bir-compliance/test'
      path: '/api/bir-compliance/test'
      fullPath: '/api/bir-compliance/test'
      preLoaderRoute: typeof ApiBirComplianceTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/invoice/': {
      id: '/api/ai/invoice/'
      path: '/api/ai/invoice'
      fullPath: '/api/ai/invoice'
      preLoaderRoute: typeof ApiAiInvoiceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
<<<<<<< HEAD
    '/api/document/$doc_id/validate': {
      id: '/api/document/$doc_id/validate'
      path: '/api/document/$doc_id/validate'
      fullPath: '/api/document/$doc_id/validate'
      preLoaderRoute: typeof ApiDocumentDoc_idValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/document/$doc_id/bir-compliance': {
      id: '/api/document/$doc_id/bir-compliance'
      path: '/api/document/$doc_id/bir-compliance'
      fullPath: '/api/document/$doc_id/bir-compliance'
      preLoaderRoute: typeof ApiDocumentDoc_idBirComplianceRouteImport
=======
    '/api/invoice/pdf/$docId': {
      id: '/api/invoice/pdf/$docId'
      path: '/api/invoice/pdf/$docId'
      fullPath: '/api/invoice/pdf/$docId'
      preLoaderRoute: typeof ApiInvoicePdfDocIdRouteImport
>>>>>>> feature/vince
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/invoice/$invoiceNo': {
      id: '/api/ai/invoice/$invoiceNo'
      path: '/api/ai/invoice/$invoiceNo'
      fullPath: '/api/ai/invoice/$invoiceNo'
      preLoaderRoute: typeof ApiAiInvoiceInvoiceNoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiChatRoute: AiChatRoute,
  DocumentUploadContractRoute: DocumentUploadContractRoute,
  DocumentUploadInvoiceRoute: DocumentUploadInvoiceRoute,
<<<<<<< HEAD
  DocumentsInvoicesRoute: DocumentsInvoicesRoute,
  ApiBirComplianceTestRoute: ApiBirComplianceTestRoute,
=======
>>>>>>> feature/vince
  ApiDocumentUploadContractRoute: ApiDocumentUploadContractRoute,
  ApiDocumentUploadInvoiceRoute: ApiDocumentUploadInvoiceRoute,
  ApiDocumentBatchBirComplianceRoute: ApiDocumentBatchBirComplianceRoute,
  ApiDocumentBatchValidateRoute: ApiDocumentBatchValidateRoute,
  ApiDocumentBirComplianceRoute: ApiDocumentBirComplianceRoute,
  ApiDocumentValidateRoute: ApiDocumentValidateRoute,
  ApiInvoiceDoc_idRoute: ApiInvoiceDoc_idRoute,
<<<<<<< HEAD
  ApiValidationConfigsRoute: ApiValidationConfigsRoute,
  ApiValidationTestRoute: ApiValidationTestRoute,
=======
  DocumentsInvoicesIdRoute: DocumentsInvoicesIdRoute,
>>>>>>> feature/vince
  ApiInvoiceIndexRoute: ApiInvoiceIndexRoute,
  DocumentsInvoicesIndexRoute: DocumentsInvoicesIndexRoute,
  ApiAiInvoiceInvoiceNoRoute: ApiAiInvoiceInvoiceNoRoute,
<<<<<<< HEAD
  ApiDocumentDoc_idBirComplianceRoute: ApiDocumentDoc_idBirComplianceRoute,
  ApiDocumentDoc_idValidateRoute: ApiDocumentDoc_idValidateRoute,
=======
  ApiInvoicePdfDocIdRoute: ApiInvoicePdfDocIdRoute,
>>>>>>> feature/vince
  ApiAiInvoiceIndexRoute: ApiAiInvoiceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
