/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocumentUploadInvoiceRouteImport } from './routes/document-upload/invoice'
import { Route as DocumentUploadContractRouteImport } from './routes/document-upload/contract'
import { Route as AiChatRouteImport } from './routes/ai/chat'
import { Route as DocumentsInvoicesIndexRouteImport } from './routes/documents/invoices/index'
import { Route as ApiInvoiceIndexRouteImport } from './routes/api/invoice/index'
import { Route as DocumentsInvoicesIdRouteImport } from './routes/documents/invoices/$id'
import { Route as ApiInvoiceDoc_idRouteImport } from './routes/api/invoice/$doc_id'
import { Route as ApiDocumentUploadInvoiceRouteImport } from './routes/api/document-upload/invoice'
import { Route as ApiDocumentUploadContractRouteImport } from './routes/api/document-upload/contract'
import { Route as ApiAiInvoiceIndexRouteImport } from './routes/api/ai/invoice/index'
import { Route as ApiInvoicePdfDocIdRouteImport } from './routes/api/invoice/pdf.$docId'
import { Route as ApiAiInvoiceInvoiceNoRouteImport } from './routes/api/ai/invoice/$invoiceNo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentUploadInvoiceRoute = DocumentUploadInvoiceRouteImport.update({
  id: '/document-upload/invoice',
  path: '/document-upload/invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentUploadContractRoute = DocumentUploadContractRouteImport.update({
  id: '/document-upload/contract',
  path: '/document-upload/contract',
  getParentRoute: () => rootRouteImport,
} as any)
const AiChatRoute = AiChatRouteImport.update({
  id: '/ai/chat',
  path: '/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsInvoicesIndexRoute = DocumentsInvoicesIndexRouteImport.update({
  id: '/documents/invoices/',
  path: '/documents/invoices/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvoiceIndexRoute = ApiInvoiceIndexRouteImport.update({
  id: '/api/invoice/',
  path: '/api/invoice/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsInvoicesIdRoute = DocumentsInvoicesIdRouteImport.update({
  id: '/documents/invoices/$id',
  path: '/documents/invoices/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvoiceDoc_idRoute = ApiInvoiceDoc_idRouteImport.update({
  id: '/api/invoice/$doc_id',
  path: '/api/invoice/$doc_id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentUploadInvoiceRoute =
  ApiDocumentUploadInvoiceRouteImport.update({
    id: '/api/document-upload/invoice',
    path: '/api/document-upload/invoice',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDocumentUploadContractRoute =
  ApiDocumentUploadContractRouteImport.update({
    id: '/api/document-upload/contract',
    path: '/api/document-upload/contract',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAiInvoiceIndexRoute = ApiAiInvoiceIndexRouteImport.update({
  id: '/api/ai/invoice/',
  path: '/api/ai/invoice/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvoicePdfDocIdRoute = ApiInvoicePdfDocIdRouteImport.update({
  id: '/api/invoice/pdf/$docId',
  path: '/api/invoice/pdf/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiInvoiceInvoiceNoRoute = ApiAiInvoiceInvoiceNoRouteImport.update({
  id: '/api/ai/invoice/$invoiceNo',
  path: '/api/ai/invoice/$invoiceNo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai/chat': typeof AiChatRoute
  '/document-upload/contract': typeof DocumentUploadContractRoute
  '/document-upload/invoice': typeof DocumentUploadInvoiceRoute
  '/api/document-upload/contract': typeof ApiDocumentUploadContractRoute
  '/api/document-upload/invoice': typeof ApiDocumentUploadInvoiceRoute
  '/api/invoice/$doc_id': typeof ApiInvoiceDoc_idRoute
  '/documents/invoices/$id': typeof DocumentsInvoicesIdRoute
  '/api/invoice': typeof ApiInvoiceIndexRoute
  '/documents/invoices': typeof DocumentsInvoicesIndexRoute
  '/api/ai/invoice/$invoiceNo': typeof ApiAiInvoiceInvoiceNoRoute
  '/api/invoice/pdf/$docId': typeof ApiInvoicePdfDocIdRoute
  '/api/ai/invoice': typeof ApiAiInvoiceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai/chat': typeof AiChatRoute
  '/document-upload/contract': typeof DocumentUploadContractRoute
  '/document-upload/invoice': typeof DocumentUploadInvoiceRoute
  '/api/document-upload/contract': typeof ApiDocumentUploadContractRoute
  '/api/document-upload/invoice': typeof ApiDocumentUploadInvoiceRoute
  '/api/invoice/$doc_id': typeof ApiInvoiceDoc_idRoute
  '/documents/invoices/$id': typeof DocumentsInvoicesIdRoute
  '/api/invoice': typeof ApiInvoiceIndexRoute
  '/documents/invoices': typeof DocumentsInvoicesIndexRoute
  '/api/ai/invoice/$invoiceNo': typeof ApiAiInvoiceInvoiceNoRoute
  '/api/invoice/pdf/$docId': typeof ApiInvoicePdfDocIdRoute
  '/api/ai/invoice': typeof ApiAiInvoiceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai/chat': typeof AiChatRoute
  '/document-upload/contract': typeof DocumentUploadContractRoute
  '/document-upload/invoice': typeof DocumentUploadInvoiceRoute
  '/api/document-upload/contract': typeof ApiDocumentUploadContractRoute
  '/api/document-upload/invoice': typeof ApiDocumentUploadInvoiceRoute
  '/api/invoice/$doc_id': typeof ApiInvoiceDoc_idRoute
  '/documents/invoices/$id': typeof DocumentsInvoicesIdRoute
  '/api/invoice/': typeof ApiInvoiceIndexRoute
  '/documents/invoices/': typeof DocumentsInvoicesIndexRoute
  '/api/ai/invoice/$invoiceNo': typeof ApiAiInvoiceInvoiceNoRoute
  '/api/invoice/pdf/$docId': typeof ApiInvoicePdfDocIdRoute
  '/api/ai/invoice/': typeof ApiAiInvoiceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai/chat'
    | '/document-upload/contract'
    | '/document-upload/invoice'
    | '/api/document-upload/contract'
    | '/api/document-upload/invoice'
    | '/api/invoice/$doc_id'
    | '/documents/invoices/$id'
    | '/api/invoice'
    | '/documents/invoices'
    | '/api/ai/invoice/$invoiceNo'
    | '/api/invoice/pdf/$docId'
    | '/api/ai/invoice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai/chat'
    | '/document-upload/contract'
    | '/document-upload/invoice'
    | '/api/document-upload/contract'
    | '/api/document-upload/invoice'
    | '/api/invoice/$doc_id'
    | '/documents/invoices/$id'
    | '/api/invoice'
    | '/documents/invoices'
    | '/api/ai/invoice/$invoiceNo'
    | '/api/invoice/pdf/$docId'
    | '/api/ai/invoice'
  id:
    | '__root__'
    | '/'
    | '/ai/chat'
    | '/document-upload/contract'
    | '/document-upload/invoice'
    | '/api/document-upload/contract'
    | '/api/document-upload/invoice'
    | '/api/invoice/$doc_id'
    | '/documents/invoices/$id'
    | '/api/invoice/'
    | '/documents/invoices/'
    | '/api/ai/invoice/$invoiceNo'
    | '/api/invoice/pdf/$docId'
    | '/api/ai/invoice/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiChatRoute: typeof AiChatRoute
  DocumentUploadContractRoute: typeof DocumentUploadContractRoute
  DocumentUploadInvoiceRoute: typeof DocumentUploadInvoiceRoute
  ApiDocumentUploadContractRoute: typeof ApiDocumentUploadContractRoute
  ApiDocumentUploadInvoiceRoute: typeof ApiDocumentUploadInvoiceRoute
  ApiInvoiceDoc_idRoute: typeof ApiInvoiceDoc_idRoute
  DocumentsInvoicesIdRoute: typeof DocumentsInvoicesIdRoute
  ApiInvoiceIndexRoute: typeof ApiInvoiceIndexRoute
  DocumentsInvoicesIndexRoute: typeof DocumentsInvoicesIndexRoute
  ApiAiInvoiceInvoiceNoRoute: typeof ApiAiInvoiceInvoiceNoRoute
  ApiInvoicePdfDocIdRoute: typeof ApiInvoicePdfDocIdRoute
  ApiAiInvoiceIndexRoute: typeof ApiAiInvoiceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document-upload/invoice': {
      id: '/document-upload/invoice'
      path: '/document-upload/invoice'
      fullPath: '/document-upload/invoice'
      preLoaderRoute: typeof DocumentUploadInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document-upload/contract': {
      id: '/document-upload/contract'
      path: '/document-upload/contract'
      fullPath: '/document-upload/contract'
      preLoaderRoute: typeof DocumentUploadContractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/chat': {
      id: '/ai/chat'
      path: '/ai/chat'
      fullPath: '/ai/chat'
      preLoaderRoute: typeof AiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/invoices/': {
      id: '/documents/invoices/'
      path: '/documents/invoices'
      fullPath: '/documents/invoices'
      preLoaderRoute: typeof DocumentsInvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invoice/': {
      id: '/api/invoice/'
      path: '/api/invoice'
      fullPath: '/api/invoice'
      preLoaderRoute: typeof ApiInvoiceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/invoices/$id': {
      id: '/documents/invoices/$id'
      path: '/documents/invoices/$id'
      fullPath: '/documents/invoices/$id'
      preLoaderRoute: typeof DocumentsInvoicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invoice/$doc_id': {
      id: '/api/invoice/$doc_id'
      path: '/api/invoice/$doc_id'
      fullPath: '/api/invoice/$doc_id'
      preLoaderRoute: typeof ApiInvoiceDoc_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/document-upload/invoice': {
      id: '/api/document-upload/invoice'
      path: '/api/document-upload/invoice'
      fullPath: '/api/document-upload/invoice'
      preLoaderRoute: typeof ApiDocumentUploadInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/document-upload/contract': {
      id: '/api/document-upload/contract'
      path: '/api/document-upload/contract'
      fullPath: '/api/document-upload/contract'
      preLoaderRoute: typeof ApiDocumentUploadContractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/invoice/': {
      id: '/api/ai/invoice/'
      path: '/api/ai/invoice'
      fullPath: '/api/ai/invoice'
      preLoaderRoute: typeof ApiAiInvoiceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invoice/pdf/$docId': {
      id: '/api/invoice/pdf/$docId'
      path: '/api/invoice/pdf/$docId'
      fullPath: '/api/invoice/pdf/$docId'
      preLoaderRoute: typeof ApiInvoicePdfDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/invoice/$invoiceNo': {
      id: '/api/ai/invoice/$invoiceNo'
      path: '/api/ai/invoice/$invoiceNo'
      fullPath: '/api/ai/invoice/$invoiceNo'
      preLoaderRoute: typeof ApiAiInvoiceInvoiceNoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiChatRoute: AiChatRoute,
  DocumentUploadContractRoute: DocumentUploadContractRoute,
  DocumentUploadInvoiceRoute: DocumentUploadInvoiceRoute,
  ApiDocumentUploadContractRoute: ApiDocumentUploadContractRoute,
  ApiDocumentUploadInvoiceRoute: ApiDocumentUploadInvoiceRoute,
  ApiInvoiceDoc_idRoute: ApiInvoiceDoc_idRoute,
  DocumentsInvoicesIdRoute: DocumentsInvoicesIdRoute,
  ApiInvoiceIndexRoute: ApiInvoiceIndexRoute,
  DocumentsInvoicesIndexRoute: DocumentsInvoicesIndexRoute,
  ApiAiInvoiceInvoiceNoRoute: ApiAiInvoiceInvoiceNoRoute,
  ApiInvoicePdfDocIdRoute: ApiInvoicePdfDocIdRoute,
  ApiAiInvoiceIndexRoute: ApiAiInvoiceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
